import { CheckBox } from "std-widgets.slint";
import { Callabler } from "../globals/callabler.slint";
import { Translations } from "../globals/translations.slint";
import { PopupBase } from "../components/popup_base.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupDelete inherits Rectangle {
    out property <length> popup_width: 420px;
    out property <length> popup_height: 210px;
    callback show_popup();

    in-out property <bool> confirm_checked: false;
    property <bool> ok_enabled: self.confirm_checked;

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> Translations.delete_text;
        enabled_ok_button: root.ok_enabled;

        VerticalLayout {
            PopupCenteredText {
                text <=> Translations.delete_confirmation_text;
            }

            HorizontalLayout {
                alignment: center;
                CheckBox {
                    text <=> Translations.delete_confirm_i_understand;
                    checked <=> root.confirm_checked;
                }
            }
        }

        ok_clicked => {
            Callabler.delete_selected_items();
        }
    }

    show_popup() => {
        root.confirm_checked = false;
        popup_window.show();
    }
}